name: polar_eo
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Dependencies for building the book
  - python=3.12
  - jupyter-book
  - ghp-import
  # - nbsphinx
  # Dependencies for running notebooks
  ## for plotting
  - matplotlib
  - polartoolkit
  ## for sea_ice_extent
  - cartopy
  - copernicusmarine
  - xarray
  - netCDF4
  - h5netcdf
  - cdo
  - numpy
  # if packages are available on conda, add with pip below
  # but ideally, make them available on conda with a conda-forge feedstock
  - pip
  # - pip:
    # - numpy