# https://jupyterbook.org/en/stable/publish/gh-pages.html

name: deploy-book

on:
  push:
    branches:
    - main
  pull_request: # allow for testing build artifcats before merge

# This job installs dependencies, builds the book, and pushes it to gh-pages
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }} # only run one of these jobs at a time
    steps:
    - uses: actions/checkout@v4

     # Install dependencies
    - name: Setup Micomamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml

    # (optional) Cache your executed notebooks between runs
    # if you have config:
    # execute:
    #   execute_notebooks: cache
    # - name: cache executed notebooks
    #   uses: actions/cache@v4
    #   with:
    #     path: _build/.jupyter_cache
    #     key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build polar_eo/

    - name: Upload book as artifact
      uses: actions/upload-artifact@v4
      with:
        name: polar_eo
        path: polar_eo/_build/html/
        retention-days: 1

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      # Only publish if the main branch
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./polar_eo/_build/html